dynamodb:
  host: http://localhost:8000
  region: us-east-1
  aws_access_key_id: fakeMyKeyId
  aws_secret_access_key: fakeSecretAccessKey
server:
  port: 8080
  servlet:
    context-path: /mercadolibre